define kyoko = Character("Kyoko", color="#003c8c")

image kyoko blushed = "kyoko/blushed.png"
image kyoko cry = "kyoko/cry.png"
image kyoko normal = "kyoko/normal.png"
image kyoko normal serious = "kyoko/normal-serious.png"
image kyoko normal speaking = "kyoko/normal-speaking.png"
image kyoko sad = "kyoko/sad.png"
image kyoko smiling = "kyoko/smiling.png"
image kyoko smiling big = "kyoko/smiling-big.png"
image kyoko smiling closedeyes = "kyoko/smiling-closedeyes.png"
image kyoko speaking = "kyoko/speaking.png"
image kyoko speaking serious = "kyoko/speaking-serious.png"

image kyoko alt blushed = "kyoko/alt/blushed.png"
image kyoko alt cry = "kyoko/alt/cry.png"
image kyoko alt dead = "kyoko/alt/dead.png"
image kyoko alt hurt = "kyoko/alt/hurt.png"
image kyoko alt loud = "kyoko/alt/loud.png"
image kyoko alt shocked = "kyoko/alt/shocked.png"
image kyoko alt speaking = "kyoko/alt/speaking.png"